### PR TITLE
Faster versions of prox_l1_mat and prox_l1_and_sum (using mex)

### PR DESCRIPTION
**Pull request by jamesfolberth**
@stephenbeckr is using TFOCS for sparse subspace clustering and these prox implementations are a bit slower than he'd like.  Stephen has previously added `shrink_mex` to improve the speed of the shrinkage operator, which is used by these proxes.

This PR speeds things up a bit further:
* Adds `shrink_mex2`, which implements the shrinkage operator with AVX intrinsics and also uses OpenMP to parallelize shrinkage over the columns of matrix inputs.  `shrink_mex` was previously used in `prox_l1_mat` and `prox_l1_and_sum`.  It has a simple interface to change the number of threads it uses.  For example,
```matlab
shrink_mex2(struct('num_threads', 4));
X = randn(1000,1000);
Y = shrink_mex2(X, 1);
```
* Adds `prox_l1_mat_optimized`, which provides the same functionality as `prox_l1_mat` but with improved runtime.  It uses `shrink_mex2` if available.  It also determines which shrinkage implementation once, when constructing the prox operator.
* Adds `prox_l1_and_sum_optimized`, which provides the same functionality as `prox_l1_and_sum` but with improved runtime.  Initially it used `shrink_mex2` and some optimized MATLAB code, but it now uses `prox_l1_and_sum_worker_mex` to do the heavy lifting.  The mex file uses AVX instrinsics for the shrinkage operation and OpenMP to parallelize work across columns of matrix inputs.  Like `shrink_mex2`, the number of threads can be controlled at runtime.
* Adds tests for the new methods in a new `tests/` directory.

Some questions for you guys:
* Should I move the `tests/` directory to private, or is it fine where it is?  When someone `addpath`s TFOCS in their `startup.m`, for example, I think `tests/` won't get added and so those tests shouldn't interfere with anyone's outside code.
* Do you want to merge the optimized versions into the existing `prox_l1_mat` and `prox_l1_and_sum`, or leave as separate implementations?  I just worry about breaking anyone else's code with a change.

### CODE REVIEW

**Comment by stephenbeckr** [comment]
@jamesfolberth   Re: question (1), I think it's OK to keep them in tests/ (or you could put that as a sub-directory of examples/, either way is OK with me).  Re: question (2), let's merge the optimized versions into the existing `prox_l1_mat` and `prox_l1_mat_sum`, as that'll simplify using it for people. Those are relatively new functions, so I don't think we'd break anyone's code.

To make the last change, do we modify the PR, or merge it and then make the change? I'm not sure what the best way is

**Comment by jamesfolberth** [comment]
I guess I'll leave them in tests.

I'll merge the changes into the existing files and ensure they fallback gracefully to the non-mex versions.  I think I may change the final argument `useMatricized` to `useMexOrMatricized` or something.

I think I can update this PR by making a new commit to the branch on my fork.

**Comment by jamesfolberth** [comment]
`prox_l1_mat` and `prox_l1_and_sum` now use the optimized code and mex workers (if available).  If the mex code isn't compiled, they fall back to pure MATLAB code (which is somewhat optimized).

I've moved `tests/` to `mexFiles/tests`, since the tests are really about verifying that the mex files are doing what we want.  I use the original (matricized) implementations in the testers as the reference implementation.  I made a symlink to `private/tfocs_prox.m` in `mexFiles/tests/private` to get the reference implementation to work.  This should be okay on *nix but may break on Windows.  Perhaps there is a better way?

I noticed that `shrink_mex` doesn't handle vector lambda/step size inputs properly (it only takes the first element).  I guess I noticed that when writing `shrink_mex2`, but didn't implement the change.  I've made the change now.  I also made the change in `prox_l1_and_sum_worker_mex`.

I've tested the code in the testers and also in your SSC repo.  This should be good to go, so I'll merge.

**Comment by stephenbeckr** [comment]
thanks @jamesfolberth !

**Pull request merged**
